### ISSUE TITLE
1.15.2 Server Crash

### ISSUE THREAD

**Issue by MokahTGS** [MrScautHD/Space-BossTools-WorkSpace#1]
Getting a server crash with Space-BossTools-1.15.2-v64-Dev-v4

https://pastebin.com/s57yFiDy

**Comment by MrScautHD** [comment]
can you send me your modpack?

**Comment by MrScautHD** [comment]
i need it for fix

**Comment by MrScautHD** [comment]
and pls the lastlog

**Comment by MokahTGS** [comment]
I'll see if I can get that for you along with the log.

**Comment by MrScautHD** [comment]
nice 👍

**Comment by MokahTGS** [comment]
Here's the log and the mod list:

Log: https://pastebin.com/pzqJ217t

Full Mod list: https://pastebin.com/ucYmbTCu

**Comment by MrScautHD** [comment]
thx but can you send me the mods in a zip file?

**Comment by MokahTGS** [comment]
No, there are hundreds.  It is not a public pack, so I can't distribute it.

**Comment by MrScautHD** [comment]
oh ok and you can not Upload on medafire and send me the link also the mods folder?

**Comment by MokahTGS** [comment]
You can get a zipped file of the mods here:  https://www.dropbox.com/s/0u4914zzee207ab/mods.7z?dl=0

**Comment by MrScautHD** [comment]
Thx i fix this in the next Update (Space-BossTools-1.15.2-v65.jar)

**Comment by MrScautHD** [comment]
This bug is now fixed! :) https://www.curseforge.com/minecraft/mc-mods/space-bosstools/files/3020729
